<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pudu_nav2_bringup</name>
  <version>0.1.0</version>
  <description>PUDU Nav2 launch, parameters, maps and lifecycle integration.</description>
  <maintainer email="robot@pudurobot.local">PUDU Robot Team</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>fast_lio</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>icp_relocalization</exec_depend>
  <exec_depend>linorobot2_gazebo</exec_depend>
  <exec_depend>linorobot2_navigation</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>pudu_nav2_plugins</exec_depend>
  <exec_depend>pudu_scurm_sim</exec_depend>
  <exec_depend>pudu_robot_description</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
